### ISSUE TITLE
一直报错，作者大大helpme

### ISSUE THREAD

**Issue by ll160803** [XiaoliChan/zerologon-Shot#3]
python3 zerologon-Shot.py whoamianony/'DC$'@192.168.1.22
python3 zerologon-Shot.py whoamianony.org/'DC$'@192.168.1.22
python3 zerologon-Shot.py DC.whoamianony.org/'DC$'@192.168.1.22
都报错，错误原因都一样
<img width="770" alt="image" src="https://github.com/XiaoliChan/zerologon-Shot/assets/88411423/3386cded-48ce-4260-9348-1c9f254db6c9">
![b86c7035657e4dea73ab98b418c3fdb0_0](https://github.com/XiaoliChan/zerologon-Shot/assets/88411423/160fc0a1-6565-4ed1-b666-df5a43857c7e)
<img width="573" alt="image" src="https://github.com/XiaoliChan/zerologon-Shot/assets/88411423/5a9ea719-fab9-403b-b7c6-76490bd93363">
这个和我本机的环境有关系吗？我是mac m2 arm架构的

**Comment by XiaoliChan** [comment]
1、试试hosts里面加上`whoamianony.org`
2、更新impacket
3、报错请提供完整截图信息，包括命令

**Comment by XiaoliChan** [comment]
@ll160803 更新了使用说明，添加了 `-dc-ip`，希望能解决你的问题
